from . import product
from . import room
from . import hallway
from . import kennel
from . import dog
from . import stay_kennel
from . import dog_stay
from . import res_partner
from . import sale_order
